on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build App
        run: ./scripts/buildprod.sh

      - name: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build docker image to GCP
        run: gcloud builds submit --tag europe-west8-docker.pkg.dev/notely-447918/notely-ar-repo/4madness7/notely:latest .

      - name: Migrate DB
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west8-docker.pkg.dev/notely-447918/notely-ar-repo/4madness7/notely:latest --region us-central1 --allow-unauthenticated --project notely-447918 --max-instances=4

